### ISSUE TITLE
我的参数都在data中带了，为什么获取不到授权令牌？

### ISSUE THREAD

**Issue by smallcat419** [baidu/baiduads-sdk#44]
问一个初级的问题……
`import urllib.parse
import urllib.request
import json

url = "https://u.baidu.com/oauth/accessToken"

header = {
        "userName" : "我的userName",
        "accessToken" : "我的accessToken"
        }

body = {
      "appId": "我的appId",
       "authCode": "我的authCode",
        "secretKey": "我的secretKey",
        "grantType": "auth_code",
        "userId": 我的userId
    }

jsonDict = {'header':header, 'body':body}
jsonStr = json.dumps(jsonDict, ensure_ascii = False)
jsonStr = jsonStr.encode('utf-8')

print(jsonDict)

headers = {'content-type': 'application/json;charset=utf-8'}
req = urllib.request.Request(url, data=jsonStr, headers=headers)
page = urllib.request.urlopen(req)
html = page.read()

jsondata = json.dumps(html.decode('UTF-8'))
#print(jsondata)
dictdata = json.loads(json.loads(jsondata))
print(dictdata)`

运行后，百度返回了错误码给我：
`{'code': 3, 'data': {}, 'message': '参数错误：授权账号 userId 不符合规范;应用 appId 不能为空;临时授权码 authCode 不能为空;应用密钥 secretKey 不能为空;！'}`

可是我的参数都在data中带了，为什么获取不到授权令牌？

**Comment by JoeCqupt** [comment]
参数问题

1. 请参考接口文档：[OAuth2.0 接口文档](https://dev2.baidu.com/content?sceneType=0&pageId=100441&nodeId=421&subhead=3.4%E3%80%81%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3)

2. 也可以使用sdk [oauth_service](https://github.com/baidu/baiduads-sdk/blob/main/python/baiduads-sdk/baiduads_manual/oauth/api/oauth_service.py#L14)
