### ISSUE TITLE
com.fasterxml.jackson.databind.Module: Provider com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule not found导致sprinboot项目无法正常启动

### ISSUE THREAD

**Issue by zhuangchongyi** [baidu/baiduads-sdk#51]
sdk版本
```
<dependency>
            <groupId>com.baidu.dev2</groupId>
            <artifactId>baiduads-sdk</artifactId>
            <version>2023.1.0</version>
        </dependency>
```
sprinboot项目无法正常启动
![image](https://github.com/baidu/baiduads-sdk/assets/50283491/ae250f6e-d43b-422c-8f47-2c04aab652ee)

报错提示com.fasterxml.jackson.databind.Module: Provider com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule not found
原因是因为我logback.xml文件配置了
```
<springProfile name="test|prod">
        <root level="info">
            <appender-ref ref="logstash"/>
        </root>
    </springProfile>
```
发现去掉之后正常可以启动
![image](https://github.com/baidu/baiduads-sdk/assets/50283491/e949f7c8-d045-4831-b9ce-57dbd79744bb)
翻了下源码发现是这里会自动加载
吐槽一下，一启动就直接挂掉，没有任何错误信息，排查了一天，最后还是在main方法try 一下，发现是没有此com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule导致的
![image](https://github.com/baidu/baiduads-sdk/assets/50283491/ae250f6e-d43b-422c-8f47-2c04aab652ee)

```
try {
            SpringApplication.run(Application.class, args);
        } catch (Throwable e) {
            e.printStackTrace();
        }
```
加完后
![image](https://github.com/baidu/baiduads-sdk/assets/50283491/76fafc00-49e5-484a-ba23-38a7cb9fef62)

现解决方案是再加个jackson-module-jaxb-annotations的依赖
```
<dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-jaxb-annotations</artifactId>
        </dependency>
```

**Comment by JoeCqupt** [comment]
看上去好像是项目中 `net.logstash.logback` 依赖 jackson相关组件引起的，应该跟SDK无关

请检查项目中以下的依赖
``` 
 <groupId>net.logstash.logback</groupId>
 <artifactId>logstash-logback-encoder</artifactId>
```
